; ========================================================================
;Each new term in the Fibonacci sequence is generated by adding the previous
;two terms. By starting with 1 and 2, the first 10 terms will be:
;
;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
;Find the sum of all the even-valued terms in the sequence which do not exceed
;four million.
; ========================================================================

;(define (fib n)
;  (if (< n 2)
;      n
;      (+ (fib (- n 1)) (fib (- n 2)))))

(define (fib n)
  (define (fib-iter a b count)
    (if (= count 0)
        b
        (fib-iter (+ a b) a (- count 1))))
  (fib-iter 2 1 n))


(define (problem-2)
  (define (loop sum-of-even i threshold)
    (let ((f (fib i)))
      (if (< threshold f)
          sum-of-even
          (loop
           (+ sum-of-even (if (= (modulo f 2) 0) f 0))
           (+ i 1)
           threshold))))
  (loop 0 0 4000000))

;gosh> (problem-2)
;4613732
